# Generated by Django 5.1 on 2025-03-20 11:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Egitmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('unvan', models.CharField(blank=True, max_length=100)),
                ('ozgecmis', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profil_resmi', models.ImageField(blank=True, null=True, upload_to='egitmenler/')),
                ('aktif', models.BooleanField(default=True)),
                ('silindi', models.BooleanField(default=False)),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Eğitmen',
                'verbose_name_plural': 'Eğitmenler',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100)),
                ('aciklama', models.TextField()),
                ('aktif', models.BooleanField(default=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('silindi', models.BooleanField(default=False)),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Soru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soru_metni', models.TextField()),
                ('soru_tipi', models.CharField(choices=[('coktan_secmeli', 'Çoktan Seçmeli'), ('dogru_yanlis', 'Doğru/Yanlış'), ('metin', 'Metin Cevaplı')], default='coktan_secmeli', max_length=20)),
                ('dogru_cevap_metni', models.TextField(blank=True, help_text='Metin tipi sorular için doğru cevap', null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('silindi', models.BooleanField(default=False)),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Soru',
                'verbose_name_plural': 'Sorular',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Gorusme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('baslik', models.CharField(max_length=255, verbose_name='Görüşme Başlığı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Görüşme Açıklaması')),
                ('baslangic_zamani', models.DateTimeField(verbose_name='Başlangıç Zamanı')),
                ('bitis_zamani', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('sure_dakika', models.PositiveIntegerField(blank=True, null=True, verbose_name='Süre (dakika)')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('aktif', 'Aktif'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi')], default='bekliyor', max_length=15, verbose_name='Durum')),
                ('giris_izni', models.CharField(choices=[('davetli', 'Sadece Davetliler'), ('herkes', 'Herkes (Link ile)')], default='davetli', max_length=15, verbose_name='Giriş İzni')),
                ('kayit_alsinmi', models.BooleanField(default=False, verbose_name='Kayıt Alınsın mı?')),
                ('kayit_url', models.URLField(blank=True, null=True, verbose_name='Kayıt URL')),
                ('jitsi_oda_adi', models.CharField(max_length=255, unique=True, verbose_name='Jitsi Oda Adı')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olusturulan_gorusmeler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Görüşme',
                'verbose_name_plural': 'Görüşmeler',
                'ordering': ['-baslangic_zamani'],
            },
        ),
        migrations.CreateModel(
            name='HaftalikHedef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Hedef Başlığı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('devam_ediyor', 'Devam Ediyor'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi')], default='bekliyor', max_length=20, verbose_name='Durum')),
                ('oncelik', models.CharField(choices=[('dusuk', 'Düşük'), ('orta', 'Orta'), ('yuksek', 'Yüksek')], default='orta', max_length=10, verbose_name='Öncelik')),
                ('hedef_turu', models.CharField(choices=[('standart', 'Standart Hedef'), ('bireysel_hedef', 'Bireysel Hedef Oluşturma'), ('ilac_yonetimi', 'İlaç Yönetim Çizelgesi'), ('gun_planlama', 'Günü Planlama')], default='standart', max_length=20, verbose_name='Hedef Türü')),
                ('ozel_veri', models.JSONField(blank=True, help_text='Hedef türüne özel veriler', null=True, verbose_name='Özel Veri')),
                ('baslama_tarihi', models.DateField(verbose_name='Başlama Tarihi')),
                ('bitis_tarihi', models.DateField(verbose_name='Bitiş Tarihi')),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('ilerleme_yuzdesi', models.IntegerField(default=0, verbose_name='İlerleme Yüzdesi')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haftalik_hedefler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Haftalık Hedef',
                'verbose_name_plural': 'Haftalık Hedefler',
                'ordering': ['-baslama_tarihi', 'oncelik'],
            },
        ),
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.CharField(max_length=255)),
                ('icerik', models.TextField()),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('okundu', models.BooleanField(default=False)),
                ('okunma_tarihi', models.DateTimeField(blank=True, null=True)),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('cevaplandi', 'Cevaplandı'), ('kapatildi', 'Kapatıldı')], default='bekliyor', max_length=20)),
                ('alici', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alinan_mesajlar', to=settings.AUTH_USER_MODEL)),
                ('cevap_mesaji', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cevaplar', to='webui.mesaj')),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_mesajlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mesaj',
                'verbose_name_plural': 'Mesajlar',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('resim', models.ImageField(blank=True, help_text='Modül için kapak resmi', null=True, upload_to='modul_resimleri/')),
                ('video_sayisi', models.PositiveSmallIntegerField(default=0)),
                ('toplam_sure', models.PositiveIntegerField(default=0, help_text='Saniye cinsinden toplam süre')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('one_cikan', models.BooleanField(default=False, help_text='Öne çıkan modül olarak işaretlenirse, giriş yapmamış kullanıcılara gösterilir')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('silindi', models.BooleanField(default=False)),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True)),
                ('egitmen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moduller', to='webui.egitmen', verbose_name='Eğitmen')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moduller', to='webui.kategori', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Modül',
                'verbose_name_plural': 'Modüller',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Secenek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secenek_metni', models.CharField(max_length=255)),
                ('dogru_mu', models.BooleanField(default=False)),
                ('aktif', models.BooleanField(default=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('silindi', models.BooleanField(default=False)),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True)),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secenekler', to='webui.soru')),
            ],
            options={
                'verbose_name': 'Seçenek',
                'verbose_name_plural': 'Seçenekler',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('aciklama', models.TextField()),
                ('video_url', models.URLField(blank=True, help_text="YouTube veya diğer video platformu URL'i (opsiyonel)", null=True)),
                ('dosya', models.FileField(blank=True, help_text='MP4, WebM veya diğer video formatında dosya yükleyebilirsiniz', null=True, upload_to='videolar/')),
                ('thumbnail_image', models.ImageField(blank=True, help_text='Video için özel kapak görseli yükleyebilirsiniz', null=True, upload_to='thumbnails/')),
                ('thumbnail_url', models.URLField(blank=True, help_text="Video için kapak görseli URL'i (opsiyonel)", null=True)),
                ('sure', models.PositiveIntegerField(help_text='Saniye cinsinden video süresi')),
                ('aktif', models.BooleanField(default=True)),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('silindi', models.BooleanField(default=False)),
                ('silinme_tarihi', models.DateTimeField(blank=True, null=True)),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videolar', to='webui.modul')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videolar',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='soru',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorular', to='webui.video'),
        ),
        migrations.CreateModel(
            name='GorusmeKatilimci',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('davet_zamani', models.DateTimeField(auto_now_add=True)),
                ('davet_durumu', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('kabul', 'Kabul Edildi'), ('red', 'Reddedildi')], default='bekliyor', max_length=15)),
                ('katilim_zamani', models.DateTimeField(blank=True, null=True)),
                ('ayrilma_zamani', models.DateTimeField(blank=True, null=True)),
                ('gorusme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='katilimcilar', to='webui.gorusme')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorusme_katilimlari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Görüşme Katılımcısı',
                'verbose_name_plural': 'Görüşme Katılımcıları',
                'unique_together': {('gorusme', 'kullanici')},
            },
        ),
        migrations.CreateModel(
            name='KullaniciIlerleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilerleme_yuzdesi', models.IntegerField(default=0)),
                ('en_yuksek_ilerleme_yuzdesi', models.IntegerField(default=0)),
                ('tamamlandi', models.BooleanField(default=False)),
                ('baslama_tarihi', models.DateTimeField(auto_now_add=True)),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webui.modul')),
            ],
            options={
                'verbose_name': 'Kullanıcı İlerlemesi',
                'verbose_name_plural': 'Kullanıcı İlerlemeleri',
                'unique_together': {('kullanici', 'modul')},
            },
        ),
        migrations.CreateModel(
            name='KullaniciCevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dogru_mu', models.BooleanField(default=False)),
                ('cevaplama_tarihi', models.DateTimeField(auto_now_add=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cevaplar', to=settings.AUTH_USER_MODEL)),
                ('secilen_secenek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webui.secenek')),
                ('soru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webui.soru')),
            ],
            options={
                'verbose_name': 'Kullanıcı Cevabı',
                'verbose_name_plural': 'Kullanıcı Cevapları',
                'unique_together': {('kullanici', 'soru')},
            },
        ),
        migrations.CreateModel(
            name='VideoIzleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamamlandi', models.BooleanField(default=False)),
                ('izleme_suresi', models.PositiveIntegerField(default=0, help_text='Saniye cinsinden izleme süresi')),
                ('son_izleme_tarihi', models.DateTimeField(auto_now=True)),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='izlemeler', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webui.video')),
            ],
            options={
                'verbose_name': 'Video İzleme',
                'verbose_name_plural': 'Video İzlemeler',
                'unique_together': {('kullanici', 'video')},
            },
        ),
    ]
