# Generated by Django 5.1 on 2025-03-20 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0002_hedefgorevi'),
    ]

    operations = [
        migrations.CreateModel(
            name='GorevKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100, verbose_name='Kategori Başlığı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('renk', models.CharField(default='primary', help_text='Bootstrap renk sınıfı (primary, success, danger, warning, info)', max_length=20, verbose_name='Renk')),
                ('simge', models.CharField(default='fas fa-tasks', help_text='FontAwesome simge sınıfı', max_length=50, verbose_name='Simge')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
            ],
            options={
                'verbose_name': 'Görev Kategorisi',
                'verbose_name_plural': 'Görev Kategorileri',
                'ordering': ['baslik'],
            },
        ),
        migrations.AddField(
            model_name='hedefgorevi',
            name='icerik',
            field=models.TextField(blank=True, null=True, verbose_name='Görev İçeriği'),
        ),
        migrations.AddField(
            model_name='hedefgorevi',
            name='oncelik',
            field=models.CharField(choices=[('dusuk', 'Düşük'), ('orta', 'Orta'), ('yuksek', 'Yüksek')], default='orta', max_length=10, verbose_name='Öncelik'),
        ),
        migrations.AddField(
            model_name='hedefgorevi',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gorevler', to='webui.gorevkategori', verbose_name='Kategori'),
        ),
    ]
