# Generated by Django 5.1.7 on 2025-03-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0003_gorevkategori_hedefgorevi_icerik_hedefgorevi_oncelik_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hedefgorevi',
            name='dinamik_icerik',
            field=models.JSONField(blank=True, null=True, verbose_name='Dinamik İçerik'),
        ),
    ]
