# Generated by Django 4.2.10 on 2025-03-23 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0004_hedefgorevi_dinamik_icerik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haftalikhedef',
            name='ozel_veri',
            field=models.TextField(blank=True, null=True, verbose_name='Özel Veri'),
        ),
    ]
