# Generated by Django 4.2.10 on 2025-03-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0005_alter_haftalikhedef_ozel_veri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hedefgorevi',
            name='dinamik_icerik',
            field=models.TextField(blank=True, null=True, verbose_name='Dinamik İçerik'),
        ),
    ]
