# Generated by Django 4.2.10 on 2025-03-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0006_alter_hedefgorevi_dinamik_icerik'),
    ]

    operations = [
        migrations.AddField(
            model_name='modul',
            name='baslangic_tarihi',
            field=models.DateField(blank=True, help_text='Bu haftanın başlangıç tarihi', null=True, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AddField(
            model_name='modul',
            name='hafta',
            field=models.PositiveSmallIntegerField(default=1, help_text='Modülün hangi haftada erişilebilir olacağı', verbose_name='Hafta'),
        ),
    ]
