# Generated by Django 4.2.10 on 2025-03-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0007_modul_baslangic_tarihi_modul_hafta'),
    ]

    operations = [
        migrations.CreateModel(
            name='HedefSablonu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Hedef Metni')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra Numarası')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Hedef Şablonu',
                'verbose_name_plural': 'Hedef Şablonları',
                'ordering': ['sira', 'id'],
            },
        ),
    ]
