# Generated by Django 4.2.10 on 2025-03-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0008_hedefsablonu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HedefSablonu',
        ),
    ]
