# Generated by Django 4.2.10 on 2025-03-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0009_delete_hedefsablonu'),
    ]

    operations = [
        migrations.AddField(
            model_name='haftalikhedef',
            name='hafta',
            field=models.PositiveSmallIntegerField(default=1, help_text='Hedefin hangi haftaya ait olduğu', verbose_name='Hafta'),
        ),
    ]
