# Generated by Django 4.2.10 on 2025-03-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0010_haftalikhedef_hafta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haftalikhedef',
            name='hafta',
        ),
    ]
