# Generated by Django 4.2.10 on 2025-03-26 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webui', '0011_remove_haftalikhedef_hafta'),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciGorevCevap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cevap_metni', models.TextField(blank=True, null=True, verbose_name='Metin Cevabı')),
                ('cevap_json', models.TextField(blank=True, null=True, verbose_name='JSON Cevabı')),
                ('tamamlandi', models.BooleanField(default=False, verbose_name='Tamamlandı')),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('gorev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanici_cevaplari', to='webui.hedefgorevi', verbose_name='Görev')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorev_cevaplari', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Görev Cevabı',
                'verbose_name_plural': 'Kullanıcı Görev Cevapları',
                'unique_together': {('kullanici', 'gorev')},
            },
        ),
    ]
