# Generated by Django 4.2.10 on 2025-03-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0012_kullanicigorevcevap'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KullaniciGorevCevap',
        ),
    ]
