# Generated by Django 4.2.10 on 2025-03-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0013_delete_kullanicigorevcevap'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='haftalikhedef',
            options={'ordering': ['-baslama_tarihi'], 'verbose_name': 'Haftalık Hedef', 'verbose_name_plural': 'Haftalık Hedefler'},
        ),
        migrations.RemoveField(
            model_name='haftalikhedef',
            name='hedef_turu',
        ),
        migrations.RemoveField(
            model_name='haftalikhedef',
            name='oncelik',
        ),
        migrations.RemoveField(
            model_name='hedefgorevi',
            name='oncelik',
        ),
    ]
