# Generated by Django 4.2.10 on 2025-03-26 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webui', '0014_alter_haftalikhedef_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciGorevCevabi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField(verbose_name='Cevap İçeriği')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('gorev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanici_cevaplari', to='webui.hedefgorevi')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorev_cevaplari', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kullanıcı Görev Cevabı',
                'verbose_name_plural': 'Kullanıcı Görev Cevapları',
                'unique_together': {('kullanici', 'gorev')},
            },
        ),
    ]
