# Generated by Django 4.2.10 on 2025-03-26 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0015_kullanicigorevcevabi'),
    ]

    operations = [
        migrations.CreateModel(
            name='KullaniciCevaplari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cevaplar', models.TextField(default='{}')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('gorev', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kullanici_cevaplari_set', to='webui.hedefgorevi')),
            ],
            options={
                'verbose_name': 'Kullanıcı Cevapları',
                'verbose_name_plural': 'Kullanıcı Cevapları',
            },
        ),
        migrations.CreateModel(
            name='DinamikTabloVerisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.TextField(default='[]')),
                ('rows', models.TextField(default='[]')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True)),
                ('gorev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tablo_verileri', to='webui.hedefgorevi')),
            ],
            options={
                'verbose_name': 'Dinamik Tablo Verisi',
                'verbose_name_plural': 'Dinamik Tablo Verileri',
            },
        ),
    ]
