# Generated by Django 4.2.10 on 2025-03-26 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webui', '0016_kullanicicevaplari_dinamiktabloverisi'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenelHedef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Hedef Başlığı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('durum', models.CharField(choices=[('bekliyor', 'Bekliyor'), ('aktif', 'Aktif'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi')], default='aktif', max_length=20, verbose_name='Durum')),
                ('ozel_veri', models.TextField(blank=True, null=True, verbose_name='Özel Veri')),
                ('baslama_tarihi', models.DateField(verbose_name='Başlama Tarihi')),
                ('bitis_tarihi', models.DateField(verbose_name='Bitiş Tarihi')),
                ('hafta', models.PositiveSmallIntegerField(default=1, help_text='Hedefin hangi haftaya ait olduğu', verbose_name='Hafta')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('olusturan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olusturulan_genel_hedefler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Genel Hedef',
                'verbose_name_plural': 'Genel Hedefler',
                'ordering': ['-baslama_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='GenelHedefGorevi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Görev Başlığı')),
                ('icerik', models.TextField(blank=True, null=True, verbose_name='Görev İçeriği')),
                ('dinamik_icerik', models.TextField(blank=True, null=True, verbose_name='Dinamik İçerik')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('hedef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gorevler', to='webui.genelhedef', verbose_name='Genel Hedef')),
                ('kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genel_gorevler', to='webui.gorevkategori', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Genel Hedef Görevi',
                'verbose_name_plural': 'Genel Hedef Görevleri',
                'ordering': ['olusturulma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='KullaniciGenelHedefIlerlemesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ilerleme_yuzdesi', models.IntegerField(default=0)),
                ('tamamlandi', models.BooleanField(default=False)),
                ('baslama_tarihi', models.DateTimeField(auto_now_add=True)),
                ('son_guncelleme', models.DateTimeField(auto_now=True)),
                ('tamamlanma_tarihi', models.DateTimeField(blank=True, null=True)),
                ('genel_hedef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanici_ilerlemeleri', to='webui.genelhedef')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genel_hedef_ilerlemeleri', to=settings.AUTH_USER_MODEL)),
                ('tamamlanan_gorevler', models.ManyToManyField(blank=True, related_name='tamamlayan_kullanicilar', to='webui.genelhedefgorevi')),
            ],
            options={
                'verbose_name': 'Kullanıcı Genel Hedef İlerlemesi',
                'verbose_name_plural': 'Kullanıcı Genel Hedef İlerlemeleri',
                'unique_together': {('kullanici', 'genel_hedef')},
            },
        ),
    ]
