# Generated by Django 4.2.10 on 2025-03-26 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0017_genelhedef_genelhedefgorevi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genelhedefgorevi',
            name='hedef',
        ),
        migrations.RemoveField(
            model_name='genelhedefgorevi',
            name='kategori',
        ),
        migrations.AlterUniqueTogether(
            name='kullanicigenelhedefilerlemesi',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='kullanicigenelhedefilerlemesi',
            name='genel_hedef',
        ),
        migrations.RemoveField(
            model_name='kullanicigenelhedefilerlemesi',
            name='kullanici',
        ),
        migrations.RemoveField(
            model_name='kullanicigenelhedefilerlemesi',
            name='tamamlanan_gorevler',
        ),
        migrations.DeleteModel(
            name='GenelHedef',
        ),
        migrations.DeleteModel(
            name='GenelHedefGorevi',
        ),
        migrations.DeleteModel(
            name='KullaniciGenelHedefIlerlemesi',
        ),
    ]
