# Generated by Django 4.2.10 on 2025-03-26 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0018_remove_genelhedefgorevi_hedef_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='haftalikhedef',
            name='kullanici',
        ),
        migrations.RemoveField(
            model_name='hedefgorevi',
            name='hedef',
        ),
        migrations.RemoveField(
            model_name='hedefgorevi',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='kullanicicevaplari',
            name='gorev',
        ),
        migrations.AlterUniqueTogether(
            name='kullanicigorevcevabi',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='kullanicigorevcevabi',
            name='gorev',
        ),
        migrations.RemoveField(
            model_name='kullanicigorevcevabi',
            name='kullanici',
        ),
        migrations.AddField(
            model_name='dinamiktabloverisi',
            name='deger',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dinamiktabloverisi',
            name='satir_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinamiktabloverisi',
            name='sutun_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinamiktabloverisi',
            name='tablo_adi',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='dinamiktabloverisi',
            unique_together={('tablo_adi', 'satir_id', 'sutun_id')},
        ),
        migrations.DeleteModel(
            name='GorevKategori',
        ),
        migrations.DeleteModel(
            name='HaftalikHedef',
        ),
        migrations.DeleteModel(
            name='KullaniciCevaplari',
        ),
        migrations.DeleteModel(
            name='KullaniciGorevCevabi',
        ),
        migrations.RemoveField(
            model_name='dinamiktabloverisi',
            name='gorev',
        ),
        migrations.RemoveField(
            model_name='dinamiktabloverisi',
            name='guncelleme_tarihi',
        ),
        migrations.RemoveField(
            model_name='dinamiktabloverisi',
            name='headers',
        ),
        migrations.RemoveField(
            model_name='dinamiktabloverisi',
            name='olusturma_tarihi',
        ),
        migrations.RemoveField(
            model_name='dinamiktabloverisi',
            name='rows',
        ),
        migrations.DeleteModel(
            name='HedefGorevi',
        ),
    ]
