# Generated by Django 4.2.10 on 2025-03-26 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webui', '0019_remove_haftalikhedef_kullanici_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HaftalikAktivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=255, verbose_name='Aktivite Başlığı')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Aktivite Açıklaması')),
                ('hafta', models.PositiveSmallIntegerField(default=1, help_text='Aktivitenin hangi haftada görüntüleneceği', verbose_name='Hafta')),
                ('tip', models.CharField(choices=[('checkbox', 'Onay Kutuları'), ('tablo', 'Tablo'), ('metin', 'Metin Alanı'), ('karma', 'Karma (Birden Fazla Tip)')], default='karma', max_length=20, verbose_name='Aktivite Tipi')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('icerik_json', models.TextField(blank=True, help_text='Aktivitenin yapısını tanımlayan JSON verisi', null=True, verbose_name='İçerik (JSON)')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('silindi', models.BooleanField(default=False, verbose_name='Silindi mi?')),
                ('olusturan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='olusturdugu_aktiviteler', to=settings.AUTH_USER_MODEL, verbose_name='Oluşturan')),
            ],
            options={
                'verbose_name': 'Haftalık Aktivite',
                'verbose_name_plural': 'Haftalık Aktiviteler',
                'ordering': ['hafta', '-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='AktiviteOgesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip', models.CharField(choices=[('checkbox', 'Onay Kutusu'), ('tablo', 'Tablo'), ('metin', 'Metin Alanı'), ('baslik', 'Başlık/Bölüm'), ('aciklama', 'Açıklama Metni')], max_length=20, verbose_name='Öğe Tipi')),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra Numarası')),
                ('baslik', models.CharField(blank=True, max_length=255, null=True, verbose_name='Öğe Başlığı/Etiketi')),
                ('aciklama', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('zorunlu', models.BooleanField(default=False, verbose_name='Zorunlu mu?')),
                ('icerik_json', models.TextField(blank=True, help_text='Öğe için ek yapılandırma (tablo boyutu, seçenekler vb.)', null=True, verbose_name='İçerik (JSON)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('silindi', models.BooleanField(default=False)),
                ('aktivite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ogeler', to='webui.haftalikaktivite', verbose_name='Bağlı Olduğu Aktivite')),
            ],
            options={
                'verbose_name': 'Aktivite Öğesi',
                'verbose_name_plural': 'Aktivite Öğeleri',
                'ordering': ['aktivite', 'sira'],
            },
        ),
        migrations.CreateModel(
            name='KullaniciAktiviteYaniti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yanitlar_json', models.TextField(verbose_name='Yanıtlar (JSON)')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('tamamlandi', models.BooleanField(default=False, verbose_name='Tamamlandı mı?')),
                ('aktivite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanici_yanitlari', to='webui.haftalikaktivite', verbose_name='Aktivite')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aktivite_yanitlari', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Aktivite Yanıtı',
                'verbose_name_plural': 'Kullanıcı Aktivite Yanıtları',
                'unique_together': {('kullanici', 'aktivite')},
            },
        ),
    ]
