# Generated by Django 5.1 on 2025-03-28 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0020_aktivite_sistemi'),
    ]

    operations = [
        migrations.AddField(
            model_name='haftalikaktivite',
            name='baslangic_tarihi',
            field=models.DateField(blank=True, help_text='Bu aktivitenin erişilebilir olacağı başlangıç tarihi', null=True, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AddField(
            model_name='haftalikaktivite',
            name='bitis_tarihi',
            field=models.DateField(blank=True, help_text='Bu aktivitenin erişilebilir olacağı son tarih', null=True, verbose_name='Bitiş Tarihi'),
        ),
    ]
