# Generated by Django 4.2.10 on 2025-04-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0021_haftalikaktivite_baslangic_tarihi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='haftalikaktivite',
            name='baslangic_tarihi',
            field=models.DateField(blank=True, help_text='Bu aktivitenin erişilebilir olacağı başlangıç tarihi (Artık kullanılmıyor, eski veriler için tutuldu)', null=True, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='haftalikaktivite',
            name='bitis_tarihi',
            field=models.DateField(blank=True, help_text='Bu aktivitenin erişilebilir olacağı son tarih (Artık kullanılmıyor, eski veriler için tutuldu)', null=True, verbose_name='Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='modul',
            name='baslangic_tarihi',
            field=models.DateField(blank=True, help_text='Bu haftanın başlangıç tarihi (Artık kullanılmıyor, eski veriler için tutuldu)', null=True, verbose_name='Başlangıç Tarihi'),
        ),
    ]
