# Generated by Django 5.1.7 on 2025-04-14 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0022_alter_haftalikaktivite_baslangic_tarihi_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kullanicicevap',
            name='degerlendiren',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='degerlendirdigi_cevaplar', to=settings.AUTH_USER_MODEL, verbose_name='Değerlendiren Kişi'),
        ),
        migrations.AddField(
            model_name='kullanicicevap',
            name='degerlendirildi',
            field=models.BooleanField(default=False, verbose_name='Değerlendirildi mi?'),
        ),
        migrations.AddField(
            model_name='kullanicicevap',
            name='degerlendirme_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Değerlendirme Tarihi'),
        ),
    ]
