# Generated by Django 4.2.10 on 2025-05-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0023_kullanicicevap_degerlendiren_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktiviteogesi',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dinamiktabloverisi',
            name='silindi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dinamiktabloverisi',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gorusme',
            name='silindi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gorusme',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gorusmekatilimci',
            name='silindi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gorusmekatilimci',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='haftalikaktivite',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kullaniciaktiviteyaniti',
            name='silindi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kullaniciaktiviteyaniti',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kullanicicevap',
            name='silindi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kullanicicevap',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kullaniciilerleme',
            name='silindi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kullaniciilerleme',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mesaj',
            name='silindi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mesaj',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videoizleme',
            name='silindi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videoizleme',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
