# Generated by Django 5.2.4 on 2025-09-21 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui', '0025_locksystem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True, verbose_name='Token')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('son_kullanma_tarihi', models.DateTimeField(verbose_name='Son Kullanma Tarihi')),
                ('kullanildi', models.BooleanField(default=False, verbose_name='Kullanıldı mı?')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Şifre Sıfırlama Token',
                'verbose_name_plural': 'Şifre Sıfırlama Tokenları',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
    ]
