# Generated by Django 5.1.7 on 2025-04-18 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=100, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Font Awesome ikon adı (örn: fa-comments)', max_length=50)),
                ('sira', models.PositiveSmallIntegerField(default=0, verbose_name='Sıra')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('ust_kategori', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_kategoriler', to='forum.forumkategori')),
            ],
            options={
                'verbose_name': 'Forum Kategorisi',
                'verbose_name_plural': 'Forum Kategorileri',
                'ordering': ['sira', 'baslik'],
            },
        ),
        migrations.CreateModel(
            name='ForumKonu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('goruntulenme', models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı')),
                ('sabit', models.BooleanField(default=False, verbose_name='Sabit Konu')),
                ('kapali', models.BooleanField(default=False, verbose_name='Kapalı (Yoruma Kapalı)')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konular', to='forum.forumkategori', verbose_name='Kategori')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_konulari', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Forum Konusu',
                'verbose_name_plural': 'Forum Konuları',
                'ordering': ['-sabit', '-olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='ForumYorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField(verbose_name='İçerik')),
                ('aktif', models.BooleanField(default=True, verbose_name='Aktif')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='forum.forumkonu', verbose_name='Konu')),
                ('ust_yorum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alt_yorumlar', to='forum.forumyorum', verbose_name='Üst Yorum')),
                ('yazar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_yorumlari', to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': 'Forum Yorumu',
                'verbose_name_plural': 'Forum Yorumları',
                'ordering': ['olusturma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='ForumBegeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_begenileri', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
                ('konu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='begeniler', to='forum.forumkonu', verbose_name='Konu')),
                ('yorum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='begeniler', to='forum.forumyorum', verbose_name='Yorum')),
            ],
            options={
                'verbose_name': 'Forum Beğeni',
                'verbose_name_plural': 'Forum Beğenileri',
                'unique_together': {('kullanici', 'konu'), ('kullanici', 'yorum')},
            },
        ),
    ]
