# Generated by Django 5.1.7 on 2025-04-21 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forumbegeni',
            name='tur',
            field=models.CharField(choices=[('like', 'Beğeni'), ('dislike', 'Beğenmeme')], default='like', max_length=10, verbose_name='Tür'),
        ),
        migrations.CreateModel(
            name='ForumGoruntulenme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Görüntülenme Tarihi')),
                ('konu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goruntulenme_kayitlari', to='forum.forumkonu', verbose_name='Konu')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goruntulenme_kayitlari', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Forum Görüntülenme',
                'verbose_name_plural': 'Forum Görüntülenmeleri',
                'unique_together': {('kullanici', 'konu')},
            },
        ),
    ]
