# Generated by Django 5.1.7 on 2025-04-24 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumbegeni_tur_forumgoruntulenme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forumkonu',
            name='onay_durumu',
            field=models.CharField(choices=[('onaylanmis', 'Onaylanmış'), ('beklemede', 'Onay Bekliyor'), ('reddedilmis', 'Reddedilmiş')], default='onaylanmis', max_length=20, verbose_name='Onay Durumu'),
        ),
        migrations.AddField(
            model_name='forumkonu',
            name='onay_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Onay Tarihi'),
        ),
        migrations.AddField(
            model_name='forumkonu',
            name='onaylayan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onayladigi_konular', to=settings.AUTH_USER_MODEL, verbose_name='Onaylayan Kullanıcı'),
        ),
        migrations.AddField(
            model_name='forumkonu',
            name='red_sebebi',
            field=models.TextField(blank=True, null=True, verbose_name='Red Sebebi'),
        ),
    ]
