# Generated by Django 4.2.10 on 2025-05-09 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forumkonu_onay_durumu_forumkonu_onay_tarihi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumkonu',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
        migrations.AddField(
            model_name='forumyorum',
            name='silinme_tarihi',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Silinme Tarihi'),
        ),
    ]
